# fly.toml app configuration file generated for anonybot on 2023-05-03T15:21:36+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "anonybot"
primary_region = "syd"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]